# isso aqui é um makefile
# para programadores isso aqui é essencial, atualmente, existem alternativas muito mais
# modernas e intuitivas, porém é sempre bom compreender o que é um makefile
# (e pra esse caso, usar qualquer outra coisa seria *absolutamente* desnecessário)

build:
	gcc -o main main.c
